name: malaysia_pulse
version: '1.0.0'
config-version: 2

profile: malaysia_pulse

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

models:
  malaysia_pulse:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
